/*Estado(IDESTADO, NOME, SIGLA)
Condição(IDCONDICAO, NOME)
Status(IDSTATUS, NOME)
Tipo(IDTIPO, NOME)
Alimento(IDALIMENTO, NOME, IDTIPO)
Cidade(IDCIDADE, NOME, IDESTADO)
Permissão(IDPERMISSAO, NOME)
Usuário(IDUSUARIO, NOME, EMAIL, TELEFONE, ENDERECO, IDENTIFICACAO, SENHA, IDPERMISSAO, IDCONDICAO, IDCIDADE)
Denuncia(IDDENUNCIA, DIA_HORA, MOTIVO, IDUSUARIO)
Alimento_doador(IDALIMENTO_DOADOR, VALIDADE, QUANTIDADE, DESCRICAO, IDUSUARIO, IDALIMENTO)
Reserva(IDRESERVA, QUANTIDADE_RESERVADA, IDSTATUS, IDUSUARIO, IDALIMENTO_DOADOR)*/

DROP DATABASE IF EXISTS tcc_alimento;

CREATE DATABASE tcc_alimento
CHARACTER SET utf8mb4
COLLATE utf8mb4_general_ci;

USE tcc_alimento;

CREATE TABLE Estado (
    IDESTADO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(30) NOT NULL,
    SIGLA VARCHAR(2) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Condicao (
    IDCONDICAO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Status (
    IDSTATUS INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Tipo (
    IDTIPO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Permissao (
    IDPERMISSAO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Cidade (
    IDCIDADE INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    IDESTADO INT,
    CONSTRAINT FK_CIDADE_ESTADO
        FOREIGN KEY (IDESTADO)
        REFERENCES Estado(IDESTADO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Usuario (
    IDUSUARIO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(30) NOT NULL,
    ENDERECO VARCHAR(150) NOT NULL,
    IDENTIFICACAO VARCHAR(20) NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    IDPERMISSAO INT,
    IDCONDICAO INT,
    IDCIDADE INT,

    CONSTRAINT FK_USUARIO_CIDADE
        FOREIGN KEY (IDCIDADE)
        REFERENCES Cidade(IDCIDADE),

    CONSTRAINT FK_USUARIO_PERMISSAO
        FOREIGN KEY (IDPERMISSAO)
        REFERENCES Permissao(IDPERMISSAO),

    CONSTRAINT FK_USUARIO_CONDICAO
        FOREIGN KEY (IDCONDICAO)
        REFERENCES Condicao(IDCONDICAO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Alimento (
    IDALIMENTO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    IDTIPO INT,

    CONSTRAINT FK_ALIMENTO_TIPO
        FOREIGN KEY (IDTIPO)
        REFERENCES Tipo(IDTIPO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Denuncia (
    IDDENUNCIA INT AUTO_INCREMENT PRIMARY KEY,
    DIA_HORA DATETIME NOT NULL,
    MOTIVO VARCHAR(1000) NOT NULL,
    IDUSUARIO INT,

    CONSTRAINT FK_DENUNCIA_USUARIO
        FOREIGN KEY (IDUSUARIO)
        REFERENCES Usuario(IDUSUARIO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Alimento_doador (
    IDALIMENTO_DOADOR INT AUTO_INCREMENT PRIMARY KEY,
    VALIDADE DATE NOT NULL,
    QUANTIDADE INT NOT NULL,
    DESCRICAO VARCHAR(1000),
    IDUSUARIO INT,
    IDALIMENTO INT,

    CONSTRAINT FK_DOADOR_USUARIO
        FOREIGN KEY (IDUSUARIO)
        REFERENCES Usuario(IDUSUARIO),

    CONSTRAINT FK_DOADOR_ALIMENTO
        FOREIGN KEY (IDALIMENTO)
        REFERENCES Alimento(IDALIMENTO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Reserva (
    IDRESERVA INT AUTO_INCREMENT PRIMARY KEY,
    QUANTIDADE_RESERVADA INT NOT NULL,
    IDSTATUS INT,
    IDUSUARIO INT,
    IDALIMENTO_DOADOR INT,

    CONSTRAINT FK_RESERVA_STATUS
        FOREIGN KEY (IDSTATUS)
        REFERENCES Status(IDSTATUS),

    CONSTRAINT FK_RESERVA_USUARIO
        FOREIGN KEY (IDUSUARIO)
        REFERENCES Usuario(IDUSUARIO),

    CONSTRAINT FK_RESERVA_ALIMENTO
        FOREIGN KEY (IDALIMENTO_DOADOR)
        REFERENCES Alimento_doador(IDALIMENTO_DOADOR)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO Permissao (NOME)
VALUES
('Doador'),
('Recebedor'),
('Administrador');

INSERT INTO Condicao (NOME)
VALUES
('Ativo'),
('Inativo'),
('Pendente');

INSERT INTO Estado (NOME, SIGLA)
VALUES
('São Paulo', 'SP'),
('Minas Gerais', 'MG'),
('Bahia', 'BA');

INSERT INTO Cidade (NOME, IDESTADO)
VALUES
('Ribeirão Preto', 1),
('Uberlândia', 2),
('Salvador', 3);

INSERT INTO Status (NOME)
VALUES
('Disponível'),
('Reservado'),
('Cancelado');

INSERT INTO Tipo (NOME)
VALUES
('Verduras'),
('Legumes'),
('Frutas'),
('Grãos'),
('Carnes'),
('Peixes'),
('Ovos'),
('Laticínios'),
('Massas'),
('Pães'),
('Bebidas'),
('Doces'),
('Temperos'),
('Congelados'),
('Embutidos'),
('Enlatados');

INSERT INTO Alimento (NOME, IDTIPO)
VALUES
('Arroz Integral', 4),
('Alface', 1),
('Suco de Laranja', 11);
/*========================================================================================--*/

INSERT INTO Usuario (NOME, EMAIL, TELEFONE, ENDERECO, IDENTIFICACAO, SENHA, IDPERMISSAO, IDCONDICAO, IDCIDADE) VALUES
('Carlos Henrique', 'carlos@gmail.com', '(16)99999-1111', 'Rua das Flores, 120 - Centro', '12345678900', '123456', 1, 1, 1),
('Mariana Souza', 'mariana@gmail.com', '(16)98888-2222', 'Av. Brasil, 450 - Jardim América', '98765432100', '654321', 2, 1, 2),
('João Pedro', 'joao@gmail.com', '(16)97777-3333', 'Rua XV de Novembro, 300 - Vila Nova', '45678912300', 'admin123', 3, 1, 1);

INSERT INTO Denuncia (DIA_HORA, MOTIVO, IDUSUARIO) VALUES
('2026-05-18 10:30:00', 'Descarte inadequado de alimentos', 2),
('2026-05-17 14:20:00', 'Registro de contato suspeito', 1),
('2026-05-16 09:10:00', 'Reclamação sobre entrega atrasada', 3);

INSERT INTO Alimento_doador (VALIDADE, QUANTIDADE, DESCRICAO, IDUSUARIO, IDALIMENTO) VALUES
('2026-06-01', 10, 'Arroz integral em sacos de 1kg', 1, 1),
('2026-05-25', 20, 'Alface fresca para saladas', 1, 2),
('2026-06-05', 15, 'Suco de laranja natural', 3, 3);

INSERT INTO Reserva (QUANTIDADE_RESERVADA, IDSTATUS, IDUSUARIO, IDALIMENTO_DOADOR) VALUES
(3, 2, 2, 1),
(5, 1, 2, 2),
(2, 3, 2, 3);

/* Ta atualizado agora */