Estado(IDESTADO, NOME, SIGLA)
Condição(IDCONDICAO, NOME)
Status(IDSTATUS, NOME)
Tipo(IDTIPO, NOME)
Alimento(IDALIMENTO, NOME, IDTIPO)
Cidade(IDCIDADE, NOME, IDESTADO)
Permissão(IDPERMISSAO, NOME)
Usuário(IDUSUARIO, NOME, EMAIL, TELEFONE, ENDERECO, IDENTIFICACAO, AUTENTIFICACAO, IDPERMISSAO, IDCONDICAO, IDCIDADE)
Denuncia(IDDENUNCIA, DIA_HORA, MOTIVO, IDUSUARIO)
Alimento_doador(IDALIMENTO_DOADOR, VALIDADE, QUANTIDADE, DESCRICAO, IDUSUARIO, IDALIMENTO)
Reserva(IDRESERVA, QUANTIDADE_RESERVADA, IDSTATUS, IDUSUARIO, IDALIMENTO_DOADOR)

CREATE DATABASE tcc_alimento;
USE tcc_alimento;

CREATE TABLE Estado (
    IDESTADO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
    SIGLA VARCHAR(2) NOT NULL
)ENGINE INNODB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Condicao (
    IDCONDICAO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(20) NOT NULL
)ENGINE INNODB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Status (
    IDSTATUS INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(20) NOT NULL
)ENGINE INNODB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Tipo (
    IDTIPO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL
)ENGINE INNODB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Alimento (
    IDALIMENTO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    IDTIPO INT,
    FOREIGN KEY (IDTIPO) REFERENCES Tipo(IDTIPO)
)ENGINE INNODB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Cidade (
    IDCIDADE INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    IDESTADO INT,
    FOREIGN KEY (IDESTADO) REFERENCES Estado(IDESTADO)
)ENGINE INNODB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Permissao (
    IDPERMISSAO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL
)ENGINE INNODB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Usuario (
    IDUSUARIO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(30) NOT NULL,
    ENDERECO VARCHAR(150) NOT NULL, -- Sera informado nome da rua, numero e bairro.
    IDENTIFICACAO VARCHAR(20) NOT NULL,
    AUTENTIFICACAO VARCHAR(255), -- Se a pessoa for doador ele nao precisa provar baixa renda 
    IDPERMISSAO INT,
    IDCONDICAO INT,
    IDCIDADE INT,
    FOREIGN KEY (IDCIDADE) REFERENCES Cidade(IDCIDADE),
    FOREIGN KEY (IDPERMISSAO) REFERENCES Permissao(IDPERMISSAO),
    FOREIGN KEY (IDCONDICAO) REFERENCES Condicao(IDCONDICAO)
)ENGINE INNODB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Denuncia (
    IDDENUNCIA INT PRIMARY KEY AUTO_INCREMENT,
    DIA_HORA DATETIME NOT NULL,
    MOTIVO VARCHAR(1000) NOT NULL,
    IDUSUARIO INT,
    FOREIGN KEY (IDUSUARIO) REFERENCES Usuario(IDUSUARIO)
)ENGINE INNODB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Alimento_doador (
    IDALIMENTO_DOADOR INT PRIMARY KEY AUTO_INCREMENT,
    VALIDADE DATE NOT NULL,
    QUANTIDADE INT NOT NULL,
    DESCRICAO VARCHAR(1000), -- O doador pode informar mais detalhes sobre o alimento, como por exemplo: se ele esta aberto ou fechado, se esta em bom estado ou se tem algum dano. 
    IDUSUARIO INT,
    IDALIMENTO INT,
    FOREIGN KEY (IDUSUARIO) REFERENCES Usuario(IDUSUARIO),
    FOREIGN KEY (IDALIMENTO) REFERENCES Alimento(IDALIMENTO)
)ENGINE INNODB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Reserva (
    IDRESERVA INT PRIMARY KEY AUTO_INCREMENT,
    QUANTIDADE_RESERVADA INT NOT NULL,
    IDSTATUS INT,
    IDUSUARIO INT,
    IDALIMENTO_DOADOR INT,
    FOREIGN KEY (IDSTATUS) REFERENCES Status(IDSTATUS),
    FOREIGN KEY (IDUSUARIO) REFERENCES Usuario(IDUSUARIO),
    FOREIGN KEY (IDALIMENTO_DOADOR) REFERENCES Alimento_doador(IDALIMENTO_DOADOR)
)ENGINE INNODB DEFAULT CHARSET=utf8mb4;

INSERT INTO Permissao VALUES ("ADMINISTRADOR", "RECEBEDOR", "DOADOR");